### ISSUE TITLE
TDD, setting up the environment for both Frontend and Backend

### ISSUE THREAD

**Issue by koh1project** [koh1project/apprenticeship_to_master#9]
### Issues:
- [x] #35 
- [ ] #36 
- [ ] #37 
- [x] #38 
- [x] #39

**Comment by kei95** [comment]
You'll need to set up a testing environment for your project. I'd recommend you work on this ticket to set it up in both FE and BE before you start implementing features.

**Comment by koh1project** [comment]
OK, I think this ticket is high priority in this week. 
I will use React Testing Library for the frontend, so I will start searching for a backend environment.

**Comment by koh1project** [comment]
- [ ] Decide a testing method for backend
- [ ] Set up testing env for Frontend
- [ ] Set up testing env for Backend

**Comment by kei95** [comment]
Probably better to create sub-task tickets for each item. Usually, in the real work environment, tickets are the granular the better. You can use this ticket as a placeholder for each small task. We call it story/epic in the real world.

**Comment by koh1project** [comment]
@kei95 Got it!
I changed this label as Epic and made related issues, and also I set up a workflow the checklist in the top section will be checked when the related issue is closed.
